### ISSUE TITLE
Nothing displays in 11.x

### ISSUE THREAD

**Issue by master-bob** [sakaicontrib/clog#12]
When attempting to use the clog tool with 11.x, based on this commit> 59c61ab0dae394793c34503a3a0cbdb656ec5559 <. After adding the clog tool a site and going to the site, nothing displays in the content box.

![image](https://cloud.githubusercontent.com/assets/6335721/14536805/3dff2b02-0242-11e6-900f-aa26dd735e14.png)

This occurred on a fresh installation.

**Comment by adrianfish** [comment]
Is there anything in the JS console?

**Comment by master-bob** [comment]
That's a great question, and I forgot to look at the time! xD

Yes, it can't find Jquery. I think this is related to the change upstream of moving JQuery to webjars.

**Comment by adrianfish** [comment]
Sorry to be a pain, but could you JIRA this? I'll try modding the js to pull the portal provided Jquery and not bother loading my own at all.

**Comment by adrianfish** [comment]
It's alright, I'll do it, no worries.
